apiVersion: v1
kind: Service
metadata:
  name: {{ include "bind9.fullname" . }}
  labels:
    {{- include "bind9.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: dns
      protocol: UDP
      name: dns
    - port: {{ .Values.service.port }}
      targetPort: dns-tcp
      protocol: TCP
      name: dns-tcp
  selector:
    {{- include "bind9.selectorLabels" . | nindent 4 }}
